# Generated by Django 3.2.5 on 2021-07-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewBatch',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('total_chicks', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'all_batch',
            },
        ),
    ]
